services:
  mongo:
    image: mongo:7
    container_name: aybey_db
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/var/lib/mongodb

volumes:
  mongo_data:
